[package]
name = "effective-spoon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.0"
tokio = { version = "1.17.0", features = ["fs"] }
futures = "0.3.21"
anyhow = "1.0.56"
